type User {
    _id: ID
    username: String!
    email: String!
    password: String!
    avatar: String
    joinDate: String
    favorites: [Post]
}

type Post {
    _id: ID,
    title: String!
    imageUrl: String
    categories: [String!]!
    description: String
    createdDate: String
    likes: Int
    createdBy: User!
    messages: Message
}

type Message {
    messageBody: String!
    messageDate: String
    messageUser: User!
}

type Query {
    getUsers: [String]
    getPosts: [Post]
}


type Mutation {
    addPost(title: String!, imageUrl: String, categories: [String]!, description: String!, creatorId: ID!):Post!
    signUp(username: String!, email: String!, password: String!):User
}